ThemeInterface:
    padding: dp(100)
    MDFloatLayout:
        padding: dp(100)
        md_bg_color: app.theme_cls.bg_light
        MDFillRoundFlatButton:
            text: "Button 1"
            pos_hint: {"center_x":0.5, "center_y":0.4}
            padding: dp(50),0,dp(50),0
            md_bg_color: app.theme_cls.primary_light
        MDFillRoundFlatButton:
            text: "Button 2"
            pos_hint: {"center_x":0.5, "center_y":0.5}
            padding: dp(50),0,dp(50),0
            md_bg_color: app.theme_cls.primary_color
        MDFillRoundFlatButton:
            text: "Button 3"
            pos_hint: {"center_x":0.5, "center_y":0.6}
            padding: dp(50),0,dp(50),0
            md_bg_color: app.theme_cls.primary_dark


<LayoutInterface>:
    padding: dp(20)
    md_bg_color: 1,0,0,0.2
    spacing: dp(20)
    orientation: "vertical"
    MDBoxLayout:
        padding: dp(20)
        md_bg_color: 1,0,0,0.2
        MDGridLayout:
            padding: dp(20)
            md_bg_color: 1,0,0,0.2
            rows: 3
            spacing: dp(20)
            MDLabel:
                text: "11"
                halign: "center"
                md_bg_color: 0,0,1,0.2
            MDLabel:
                text: "12"
                halign: "center"
                md_bg_color: 0,0,1,0.2
            MDLabel:
                text: "21"
                halign: "center"
                md_bg_color: 0,0,1,0.2

            MDLabel:
                text: "22"
                halign: "center"
                md_bg_color: 0,0,1,0.2
            MDLabel:
                text: "31"
                halign: "center"
                md_bg_color: 0,0,1,0.2
            MDLabel:
                text: "32"
                halign: "center"
                md_bg_color: 0,0,1,0.2
    MDBoxLayout:
        padding: dp(20)
        md_bg_color: 1,0,0,0.2
        ScrollView:
            do_scroll_y:True
            MDStackLayout:
                size_hint_y:None
                height: self.minimum_height
                padding: dp(20)
                md_bg_color: 1,0,0,0.2
                spacing: dp(20)
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2
                MDLabel:
                    size_hint:None,None
                    size: dp(200),dp(50)
                    text: "00"
                    halign: "center"
                    md_bg_color: 0,0,1,0.2


<Interface>:
    orientation: "vertical"
    MDLabel:
        md_bg_color: 0.4,0.5,0.2,1
        halign: "center"
        size_hint: None,None
        size: 200, self.texture_size[1]
        pos_hint: {"center_x":0.5,"center_y":0.5}
        text: "Hello World!"